theme: minima
title: Ideas y pruebas
author: Mpaz
email: mpazlaboratorio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Un sitio donde poner ideas y pruebas

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
